// Code generated by protoc-gen-go. DO NOT EDIT.
// source: miniprogram.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMiniprogramRequest struct {
	ShopId               uint64   `protobuf:"varint,1,opt,name=shopId,proto3" json:"shopId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMiniprogramRequest) Reset()         { *m = GetMiniprogramRequest{} }
func (m *GetMiniprogramRequest) String() string { return proto.CompactTextString(m) }
func (*GetMiniprogramRequest) ProtoMessage()    {}
func (*GetMiniprogramRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f7d93eecfc381d, []int{0}
}

func (m *GetMiniprogramRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMiniprogramRequest.Unmarshal(m, b)
}
func (m *GetMiniprogramRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMiniprogramRequest.Marshal(b, m, deterministic)
}
func (m *GetMiniprogramRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMiniprogramRequest.Merge(m, src)
}
func (m *GetMiniprogramRequest) XXX_Size() int {
	return xxx_messageInfo_GetMiniprogramRequest.Size(m)
}
func (m *GetMiniprogramRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMiniprogramRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMiniprogramRequest proto.InternalMessageInfo

func (m *GetMiniprogramRequest) GetShopId() uint64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

type GetMiniprogramReply struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	OriginalId           string   `protobuf:"bytes,3,opt,name=originalId,proto3" json:"originalId,omitempty"`
	Err                  *Error   `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMiniprogramReply) Reset()         { *m = GetMiniprogramReply{} }
func (m *GetMiniprogramReply) String() string { return proto.CompactTextString(m) }
func (*GetMiniprogramReply) ProtoMessage()    {}
func (*GetMiniprogramReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f7d93eecfc381d, []int{1}
}

func (m *GetMiniprogramReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMiniprogramReply.Unmarshal(m, b)
}
func (m *GetMiniprogramReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMiniprogramReply.Marshal(b, m, deterministic)
}
func (m *GetMiniprogramReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMiniprogramReply.Merge(m, src)
}
func (m *GetMiniprogramReply) XXX_Size() int {
	return xxx_messageInfo_GetMiniprogramReply.Size(m)
}
func (m *GetMiniprogramReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMiniprogramReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetMiniprogramReply proto.InternalMessageInfo

func (m *GetMiniprogramReply) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetMiniprogramReply) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GetMiniprogramReply) GetOriginalId() string {
	if m != nil {
		return m.OriginalId
	}
	return ""
}

func (m *GetMiniprogramReply) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// 错误信息
type Error struct {
	// 错误码
	ErrorCode uint32 `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 展示给开发这记录日志用的错误信息
	ErrorMessageForDeveloper string `protobuf:"bytes,2,opt,name=errorMessageForDeveloper,proto3" json:"errorMessageForDeveloper,omitempty"`
	// 展示给用户查看的错误信息
	ErrorMessageForUser  string   `protobuf:"bytes,3,opt,name=errorMessageForUser,proto3" json:"errorMessageForUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5f7d93eecfc381d, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Error) GetErrorMessageForDeveloper() string {
	if m != nil {
		return m.ErrorMessageForDeveloper
	}
	return ""
}

func (m *Error) GetErrorMessageForUser() string {
	if m != nil {
		return m.ErrorMessageForUser
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMiniprogramRequest)(nil), "protos.GetMiniprogramRequest")
	proto.RegisterType((*GetMiniprogramReply)(nil), "protos.GetMiniprogramReply")
	proto.RegisterType((*Error)(nil), "protos.Error")
}

func init() { proto.RegisterFile("miniprogram.proto", fileDescriptor_d5f7d93eecfc381d) }

var fileDescriptor_d5f7d93eecfc381d = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4b, 0x4f, 0x02, 0x31,
	0x14, 0x85, 0xad, 0x3c, 0x12, 0x2e, 0x61, 0xe1, 0x45, 0x49, 0xe3, 0x93, 0xcc, 0x8a, 0x15, 0x1a,
	0xdc, 0xb9, 0xf4, 0x19, 0x16, 0x6c, 0x6a, 0x74, 0x3f, 0x3a, 0x37, 0xe3, 0x24, 0x03, 0xb7, 0xde,
	0x8e, 0x26, 0xb3, 0xf7, 0x1f, 0xf8, 0x87, 0x0d, 0x9d, 0x12, 0x90, 0x30, 0xab, 0xf6, 0x9c, 0xaf,
	0x8f, 0xd3, 0x53, 0x38, 0x98, 0x67, 0x8b, 0xcc, 0x0a, 0xa7, 0x12, 0xcf, 0xc7, 0x56, 0xb8, 0x60,
	0x6c, 0xfb, 0xc1, 0x45, 0x97, 0x70, 0xf4, 0x44, 0xc5, 0x6c, 0xcd, 0x0d, 0x7d, 0x7e, 0x91, 0x2b,
	0x70, 0x00, 0x6d, 0xf7, 0xc1, 0x76, 0x9a, 0x68, 0x35, 0x54, 0xa3, 0xa6, 0x09, 0x2a, 0xfa, 0x51,
	0xd0, 0xdf, 0xde, 0x61, 0xf3, 0x12, 0x0f, 0xa1, 0x15, 0xdb, 0xd5, 0xf2, 0x8e, 0xa9, 0x84, 0x3f,
	0x85, 0xde, 0x85, 0x0a, 0xbd, 0xef, 0xed, 0xa0, 0xf0, 0x1c, 0x80, 0x25, 0x4b, 0xb3, 0x45, 0x9c,
	0x4f, 0x13, 0xdd, 0xf0, 0x6c, 0xc3, 0xc1, 0x0b, 0x68, 0x90, 0x88, 0x6e, 0x0e, 0xd5, 0xa8, 0x3b,
	0xe9, 0x55, 0x99, 0xdd, 0xf8, 0x41, 0x84, 0xc5, 0x2c, 0x49, 0xf4, 0xab, 0xa0, 0xe5, 0x25, 0x9e,
	0x42, 0x87, 0x96, 0x93, 0x3b, 0x4e, 0xc8, 0x5f, 0xde, 0x33, 0x6b, 0x03, 0x6f, 0x40, 0x7b, 0x31,
	0x23, 0xe7, 0xe2, 0x94, 0x1e, 0x59, 0xee, 0xe9, 0x9b, 0x72, 0xb6, 0x24, 0x21, 0x52, 0x2d, 0xc7,
	0x2b, 0xe8, 0x6f, 0xb1, 0x17, 0x47, 0x12, 0xd2, 0xee, 0x42, 0x13, 0x82, 0xee, 0x46, 0x31, 0xf8,
	0x0a, 0x83, 0xff, 0x55, 0xdd, 0x96, 0xcf, 0xbe, 0x45, 0x3c, 0x5b, 0x3d, 0x69, 0x67, 0xf9, 0xc7,
	0x27, 0x75, 0xd8, 0xe6, 0x65, 0xb4, 0xf7, 0x56, 0x7d, 0xde, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfb, 0xff, 0x27, 0xf4, 0xd8, 0x01, 0x00, 0x00,
}
