// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: state.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StatusController service

type StatusControllerService interface {
	Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingReply, error)
}

type statusControllerService struct {
	c    client.Client
	name string
}

func NewStatusControllerService(name string, c client.Client) StatusControllerService {
	return &statusControllerService{
		c:    c,
		name: name,
	}
}

func (c *statusControllerService) Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingReply, error) {
	req := c.c.NewRequest(c.name, "StatusController.Ping", in)
	out := new(PingReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StatusController service

type StatusControllerHandler interface {
	Ping(context.Context, *PingRequest, *PingReply) error
}

func RegisterStatusControllerHandler(s server.Server, hdlr StatusControllerHandler, opts ...server.HandlerOption) error {
	type statusController interface {
		Ping(ctx context.Context, in *PingRequest, out *PingReply) error
	}
	type StatusController struct {
		statusController
	}
	h := &statusControllerHandler{hdlr}
	return s.Handle(s.NewHandler(&StatusController{h}, opts...))
}

type statusControllerHandler struct {
	StatusControllerHandler
}

func (h *statusControllerHandler) Ping(ctx context.Context, in *PingRequest, out *PingReply) error {
	return h.StatusControllerHandler.Ping(ctx, in, out)
}
